### ISSUE TITLE
Spurious kubediff due to CPU resources

### ISSUE THREAD

**Issue by jml** [weaveworks/kubediff#33]
We are currently seeing this kubediff on prod:

```
## scope/pipe (Deployment)

.spec.template.spec.containers: 'element [0]' missing
## monitoring/alertmanager (Deployment)

.spec.template.spec.containers: 'element [0]' missing
```

AFAICT, this is because for scope/pipe, the YAML file says:

```yaml
        resources:
          requests:
            cpu: 0.5
```

But the k8s object says:

```yaml
        resources:
          requests:
            cpu: 500m
```

Despite being freshly applied.

Since this difference isn't meaningful, it shouldn't be reported.
