### ISSUE TITLE
Field removed from local configmap is not detected as a change by Kubediff

### ISSUE THREAD

**Issue by mgarstecki** [weaveworks/kubediff#91]
I've got the following configmap in my cluster:
```
kc get cm test-mat -o yaml
apiVersion: v1
data:
  CONTINENT: EU
  ENV: PREPROD
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"CONTINENT":"EU","ENV":"PREPROD"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"test-mat","namespace":"preprod"}}
  creationTimestamp: 2019-05-17T14:01:25Z
  name: test-mat
  namespace: preprod
  [...]
```

And the corresponding manifest, but with the `PREPROD` field removed:
```
$ cat test.yml
kind: ConfigMap
metadata:
  name: test-mat
data:
  CONTINENT: EU
```

Wen I run Kubediff, it doesn't detect the change between the resource and the manifest:
```bash
$ ~/kubediff/kubediff test.yml
$
```

I expected the missing field in my local config to be detected as a difference.
